<?php
include APP_PATH . "/views/header1.phtml";

?>

<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4" style="height: 100vh;">
    <div class="container-fluid px-1 px-md-4 py-5 mx-auto">
        <div class="row d-flex justify-content-center px-3">
            <div class="card" style="background-image: url('https://i.imgur.com/dpqZJV5.jpg');
    background-size: cover;
    width: 600px;
    height: 350px;
    border-radius: 20px;
    box-shadow: 0px 8px 16px 4px #9E9E9E;
    margin-top: 50px;
    margin-bottom: 50px;
    color: white">
                <h2 class="ml-auto mr-4 mt-3 mb-0">Air Quality</h2>
                <p class="ml-auto mr-4 mb-0 med-font"><b>CO: </b><?php echo $data["current"]["air_quality"]["co"] ?></p>

                <p class="ml-auto mr-4 mb-0 med-font"><b>NO<sub>2</sub></b> <?php echo $data["current"]["air_quality"]["no2"] ?></p>
                <p class="ml-auto mr-4 mb-0 med-font"><b>O<sub>3</sub></b> <?php echo $data["current"]["air_quality"]["o3"] ?></p>
                <p class="ml-auto mr-4 mb-0 med-font"><b>SO<sub>2</sub></b> <?php echo $data["current"]["air_quality"]["so2"] ?></p>
                <p class="ml-auto mr-4 mb-0 med-font"><b>pm2_5:</b> <?php echo $data["current"]["air_quality"]["pm2_5"] ?></p>
                <p class="ml-auto mr-4 mb-0 med-font"><b>us-epa-index: </b><?php echo $data["current"]["air_quality"]["us-epa-index"] ?></p>
                <p class="ml-auto mr-4 mb-0 med-font"><b>gb-defra-index:</b> <?php echo $data["current"]["air_quality"]["gb-defra-index"] ?></p>
                <p class="time-font mb-0 ml-4 mt-auto">08:30 <span class="sm-font">AM</span></p>
                <p class="ml-4 mb-4">Wednesday, 18 October 2019</p>
            </div>
        </div>
    </div>
</main>