<?php
include APP_PATH . "/views/header.phtml";
?>
<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4" style="height: 100vh;">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap 
      align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Search Location</h1>

    </div>

    <?php
    echo $this->tag->form(
        [
            "index/viewResult",
            "method" => "post",
            "class" => "row g-3"
        ]
    ); ?>

    <div class="col-md-6">
        <label for="floatingInput">Location
            <?php echo $this->tag->textField(["name", "id" => "floatingInput", "class" => "form-control", "required" => "true"]); ?>
        </label>
    </div>

    <div class="col-12">
        <?php echo $this->tag->submitButton(["Get Locations", "class" => "btn btn-primary", "name" => "submit"]); ?>
    </div>

    </form>
    <div class="alert alert-<?php echo $success === true ? 'success' : 'danger'; ?>" <?php echo isset($success) === true ? '' : 'hidden'; ?>>
        <?php echo $message; ?>
    </div>
</main>

</body>

</html>