<?php
$url = $this->request->get("url");
?>
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Hugo 0.88.1">
  <title>Dashboard Template · Bootstrap v5.1</title>

  <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/dashboard/">

  <!-- Bootstrap core CSS -->
  <link href="../node_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">

  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }

    main {
      /* background-image: url("../../../public/images/images.jpeg"); */
      background: rgb(196, 130, 159);
      background: radial-gradient(circle, rgba(196, 130, 159, 0.7679446778711485) 31%, rgba(148, 187, 233, 1) 100%);
      background-repeat: no-repeat;
      background-size: cover;
      color: white;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }

    @import url('https://fonts.googleapis.com/css2?family=Marcellus&display=swap');

    .div1 {
      background: url('./../../public/images/weather.jpeg');
      background-repeat: no-repeat;
      background-size: cover;
      background-attachment: local;
      border-radius: 16px 16px 0 0
    }

    .card {
      border-radius: 15px;
      color: #6f707d
    }



    .div2 {
      height: 30px;
      background-color: #9fe0fa;
      border-radius: 0 0 15px 15px
    }

    h1 {
      font-size: 65px
    }

    sup {
      font-size: 17px;
      position: relative;
      top: -2rem
    }

    *:focus {
      outline: none
    }

    .padding {
      padding: 10rem !important;
      margin-left: 200px
    }


    .card-text:last-child {
      margin-bottom: 0
    }

    .mdi {
      display: inline-block;
      font-family: 'weathericons';
      font-style: normal;
      font-weight: normal;
      line-height: 1;
      -webkit-font-smoothing: antialiased;
      -moz-osx-font-smoothing: grayscale
    }

    .gradient-custom {
      /* Chrome 10-25, Safari 5.1-6 */
      background: -webkit-linear-gradient(to right, rgba(255, 255, 255, 1), rgba(255, 236, 210, 1));

      /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
      background: linear-gradient(to right, rgba(255, 255, 255, 1), rgba(255, 236, 210, 1))
    }

    .carousel-indicators li {
      background-color: #282828;
      width: 7px;
      height: 7px;
      border-radius: 50%;
    }
  </style>


  <!-- Custom styles for this template -->
  <link href="<?php echo URLROOT ?>assets/css/dashboard.css" rel="stylesheet">
</head>

<body>

  <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">Company name</a>
    <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <input class="form-control form-control-dark w-100" id="myInput" type="text" placeholder="Search" aria-label="Search">
    <div class="navbar-nav">
      <div class="nav-item text-nowrap">
        <a class="nav-link px-3 text-white btn btn-danger" href="<?php echo URLROOT ?>login/signout">Sign out</a>
      </div>
    </div>
  </header>

  <div class="container-fluid">
    <div class="row">
      <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
        <div class="position-sticky pt-3">
          <ul class="nav flex-column">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="<?php echo URLROOT . 'index' ?>">
                <span data-feather="home"></span>
                Search Location
              </a>
            </li>
            <hr>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="<?php echo URLROOT . 'index/currentWeather?url=' . $url ?>">
                <span data-feather="home"></span>
                Current Weather
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="<?php echo URLROOT . 'index/forecast?url=' . $url ?>">
                Forecast
              </a>
            </li>

            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="<?php echo URLROOT . 'index/history?url=' . $url ?>">
                <span data-feather="home"></span>
                History
              </a>
            </li>

            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="<?php echo URLROOT . 'index/timezone?url=' . $url ?>">
                <span data-feather="home"></span>
                Time Zone
              </a>
            </li>

            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="<?php echo URLROOT . 'index/sports?url=' . $url ?>">
                <span data-feather="home"></span>
                Sports
              </a>
            </li>

            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="<?php echo URLROOT . 'index/astronomy?url=' . $url ?>">
                <span data-feather="home"></span>
                Astronomy
              </a>
            </li>

            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="<?php echo URLROOT . 'index/alert?url=' . $url ?>">
                <span data-feather="home"></span>
                Weather Alerts
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="<?php echo URLROOT . 'index/airquality?url=' . $url ?>">
                <span data-feather="home"></span>
                Air Quality
              </a>
            </li>



          </ul>
        </div>
      </nav>